name: "Get Working Directory"
description: "Get the working directory of the commit"
inputs:
  depth:
    description: "Number of paths to dig"
    required: true
    default: "2"
  commit-hash:
    description: "Commit hash of running commit"
    required: false
    default: ${{ github.sha }}
outputs:
  working-dir:
    description: "The current working directory"
runs:
  using: "node12"
  main: "index.js"
